# Generated by Django 5.0 on 2024-01-29 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('livro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('quantidade_paginas', models.IntegerField()),
                ('categoria', models.CharField(max_length=200)),
                ('pagina_atual', models.IntegerField()),
                ('concluido', models.BooleanField(default=False)),
                ('imagem', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('historico_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_leitura', models.DateTimeField()),
                ('pagina_atual', models.IntegerField()),
                ('data_meta', models.DateTimeField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ColecaoPessoal',
            fields=[
                ('colecao_id', models.AutoField(primary_key=True, serialize=False)),
                ('livros', models.ManyToManyField(to='api.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
