# Generated by Django 5.0 on 2023-12-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [

    ]
